### ISSUE TITLE
Hook up React Native app with Firebase app

### ISSUE THREAD

**Issue by rossedfort** [blakeworsley/blueSwimmer#3]
Integrate the existing react native app created in #1 with the firebase app created in #2.

_Acceptance Criteria_
- Necessary packages are installed in the react native app
- Necessary code is added to instantiate the firebase instance in the react native app.
- You should be able to hit the firebase database from the react native app

_References_
- https://firebase.googleblog.com/2016/01/the-beginners-guide-to-react-native-and_84.html 
- https://firebase.googleblog.com/2016/07/firebase-react-native.html
- https://firebase.googleblog.com/2015/05/firebase-now-works-with-react-native_40.html
- https://github.com/davideast/firebase-react-native-sample

**Comment by rossedfort** [comment]
Hey @blakeworsley I see this has the `ready` label, but it is dependent on issue #2.. is issue #2 done?

**Comment by blakeworsley** [comment]
I am attempting to set up an authentication for the 'swimmer' to sign in using google. This looks to me like this is the next issue. I am a bit confused on how to hit the firebase database without authenticating a user?

**Comment by rossedfort** [comment]
I think you did most of the work for this issue in #2 This can close as long as you can hit the API endpoint for the DB, even if you get an error response.
